"""Add size column to Cart and OrderItem

Revision ID: 17251aa2a5d9
Revises: 6bf8ffa3d2e0
Create Date: 2025-04-26 21:42:06.694782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17251aa2a5d9'
down_revision = '6bf8ffa3d2e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.add_column(sa.Column('size', sa.String(length=5), nullable=True))

    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('size', sa.String(length=5), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.drop_column('size')

    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.drop_column('size')

    # ### end Alembic commands ###
