"""Add foreign key constraint names

Revision ID: 1f02ce3721f4
Revises: cdf777880781
Create Date: 2025-06-03 16:27:01.803078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f02ce3721f4'
down_revision = 'cdf777880781'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_product')
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('sale_price',
               existing_type=sa.FLOAT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('sale_price',
               existing_type=sa.FLOAT(),
               nullable=False)

    op.create_table('_alembic_tmp_product',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('product_name', sa.VARCHAR(length=150), nullable=False),
    sa.Column('price', sa.FLOAT(), nullable=False),
    sa.Column('sale_price', sa.FLOAT(), nullable=True),
    sa.Column('description', sa.VARCHAR(length=1000), nullable=False),
    sa.Column('category', sa.VARCHAR(length=150), nullable=False),
    sa.Column('quantity', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('product_picture', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
