"""Add email, phone, and notes to Order

Revision ID: 6bf8ffa3d2e0
Revises: bcb3649110d9
Create Date: 2025-04-19 22:31:55.108005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bf8ffa3d2e0'
down_revision = 'bcb3649110d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('notes')
        batch_op.drop_column('phone')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
